version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: go_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

